"""add_season_coverage_metadata

Revision ID: 2534917a8a8e
Revises: 6159d16e3d7a
Create Date: 2026-05-14 15:38:39.510036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2534917a8a8e'
down_revision: Union[str, Sequence[str], None] = '6159d16e3d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('status', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('seasons', sa.Column('coverage_confidence', sa.Float(), nullable=True))
    op.add_column('seasons', sa.Column('last_audit_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'last_audit_at')
    op.drop_column('seasons', 'coverage_confidence')
    op.drop_column('seasons', 'is_verified')
    op.drop_column('seasons', 'status')
    # ### end Alembic commands ###
