"""Add unique constraint to circuit_ref

Revision ID: 573ee8f9cab6
Revises: f16a913c4287
Create Date: 2026-04-23 00:51:28.220575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573ee8f9cab6'
down_revision: Union[str, Sequence[str], None] = 'f16a913c4287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'circuits', ['circuit_ref'])
    op.drop_index(op.f('idx_lap_times_race_driver'), table_name='lap_times')
    op.drop_index(op.f('idx_races_year'), table_name='races')
    op.drop_index(op.f('idx_results_driver_id'), table_name='results')
    op.drop_index(op.f('idx_results_race_id'), table_name='results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_results_race_id'), 'results', ['race_id'], unique=False)
    op.create_index(op.f('idx_results_driver_id'), 'results', ['driver_id'], unique=False)
    op.create_index(op.f('idx_races_year'), 'races', ['year'], unique=False)
    op.create_index(op.f('idx_lap_times_race_driver'), 'lap_times', ['race_id', 'driver_id'], unique=False)
    op.drop_constraint(None, 'circuits', type_='unique')
    # ### end Alembic commands ###
