"""Phase 3: State Intelligence & Operational Metadata

Revision ID: 6159d16e3d7a
Revises: ec4cf9a427cf
Create Date: 2026-05-14 13:16:41.113319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6159d16e3d7a'
down_revision: Union[str, Sequence[str], None] = 'ec4cf9a427cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('stint_number', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(), nullable=True),
    sa.Column('start_lap', sa.Integer(), nullable=True),
    sa.Column('end_lap', sa.Integer(), nullable=True),
    sa.Column('tyre_age_at_start', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('constructor_standings', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('driver_standings', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('status', sa.String(), nullable=True))
    op.add_column('races', sa.Column('telemetry_available', sa.Boolean(), nullable=True))
    op.add_column('races', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('ingestion_version', sa.String(), nullable=True))
    op.add_column('results', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'last_updated')
    op.drop_column('races', 'ingestion_version')
    op.drop_column('races', 'last_updated')
    op.drop_column('races', 'telemetry_available')
    op.drop_column('races', 'status')
    op.drop_column('driver_standings', 'last_updated')
    op.drop_column('constructor_standings', 'last_updated')
    op.drop_table('stints')
    op.drop_table('platform_health')
    # ### end Alembic commands ###
