"""add_race_detail_fields

Revision ID: 67f570151af0
Revises: 70e8f65a32ce
Create Date: 2026-05-08 00:10:40.271865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f570151af0'
down_revision: Union[str, Sequence[str], None] = '70e8f65a32ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifying', sa.Column('q1', sa.String(), nullable=True))
    op.add_column('qualifying', sa.Column('q2', sa.String(), nullable=True))
    op.add_column('qualifying', sa.Column('q3', sa.String(), nullable=True))
    op.add_column('races', sa.Column('laps', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('time', sa.String(), nullable=True))
    op.add_column('results', sa.Column('milliseconds', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fastest_lap', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fastest_lap_time', sa.String(), nullable=True))
    op.add_column('results', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'status')
    op.drop_column('results', 'fastest_lap_time')
    op.drop_column('results', 'fastest_lap')
    op.drop_column('results', 'milliseconds')
    op.drop_column('results', 'time')
    op.drop_column('races', 'laps')
    op.drop_column('qualifying', 'q3')
    op.drop_column('qualifying', 'q2')
    op.drop_column('qualifying', 'q1')
    # ### end Alembic commands ###
