"""add_circuit_personality_and_race_sessions

Revision ID: 70e8f65a32ce
Revises: b4c304ec3510
Create Date: 2026-05-07 23:58:03.981557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e8f65a32ce'
down_revision: Union[str, Sequence[str], None] = 'b4c304ec3510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('overtaking_difficulty', sa.Float(), nullable=True))
    op.add_column('circuits', sa.Column('downforce_level', sa.String(), nullable=True))
    op.add_column('circuits', sa.Column('tire_degradation', sa.String(), nullable=True))
    op.add_column('circuits', sa.Column('weather_volatility', sa.Float(), nullable=True))
    op.add_column('circuits', sa.Column('safety_car_probability', sa.Float(), nullable=True))
    op.add_column('circuits', sa.Column('top_speed_level', sa.String(), nullable=True))
    op.add_column('circuits', sa.Column('atmosphere_description', sa.String(), nullable=True))
    op.add_column('races', sa.Column('fp1_date', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('fp2_date', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('fp3_date', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('qualifying_date', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('sprint_date', sa.DateTime(), nullable=True))
    op.add_column('races', sa.Column('analytics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'analytics')
    op.drop_column('races', 'sprint_date')
    op.drop_column('races', 'qualifying_date')
    op.drop_column('races', 'fp3_date')
    op.drop_column('races', 'fp2_date')
    op.drop_column('races', 'fp1_date')
    op.drop_column('circuits', 'atmosphere_description')
    op.drop_column('circuits', 'top_speed_level')
    op.drop_column('circuits', 'safety_car_probability')
    op.drop_column('circuits', 'weather_volatility')
    op.drop_column('circuits', 'tire_degradation')
    op.drop_column('circuits', 'downforce_level')
    op.drop_column('circuits', 'overtaking_difficulty')
    # ### end Alembic commands ###
