"""Fix Race circuit_id to circuit_ref

Revision ID: b4c304ec3510
Revises: 573ee8f9cab6
Create Date: 2026-04-23 01:11:23.240402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c304ec3510'
down_revision: Union[str, Sequence[str], None] = '573ee8f9cab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('circuit_ref', sa.String(), nullable=True))
    op.drop_constraint(op.f('races_circuit_id_fkey'), 'races', type_='foreignkey')
    op.create_foreign_key(None, 'races', 'circuits', ['circuit_ref'], ['circuit_ref'])
    op.drop_column('races', 'circuit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('circuit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.create_foreign_key(op.f('races_circuit_id_fkey'), 'races', 'circuits', ['circuit_id'], ['circuit_id'])
    op.drop_column('races', 'circuit_ref')
    # ### end Alembic commands ###
